In [ ]:
import pandas as pd
data=pd.read_csv('/content/Indian Liver Patient Dataset (ILPD).csv')
data

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,A/G Ratio,Selector
0,65,Female,0.7,0.1,187,16,18,6.8,3.3,0.90,1
1,62,Male,10.9,5.5,699,64,100,7.5,3.2,0.74,1
2,62,Male,7.3,4.1,490,60,68,7.0,3.3,0.89,1
3,58,Male,1.0,0.4,182,14,20,6.8,3.4,1.00,1
4,72,Male,3.9,2.0,195,27,59,7.3,2.4,0.40,1
...,...,...,...,...,...,...,...,...,...,...,...
578,60,Male,0.5,0.1,500,20,34,5.9,1.6,0.37,2
579,40,Male,0.6,0.1,98,35,31,6.0,3.2,1.10,1
580,52,Male,0.8,0.2,245,48,49,6.4,3.2,1.00,1
581,31,Male,1.3,0.5,184,29,32,6.8,3.4,1.00,1
582,38,Male,1.0,0.3,216,21,24,7.3,4.4,1.50,2

In [ ]:
target=data['Selector']
target.head()

0    1
1    1
2    1
3    1
4    1
Name: Selector, dtype: int64

In [ ]:
x=data.drop('Selector',axis=1)
x.head()

   Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB  A/G Ratio
0   65  Female   0.7  0.1      187    16    18  6.8  3.3       0.90
1   62    Male  10.9  5.5      699    64   100  7.5  3.2       0.74
2   62    Male   7.3  4.1      490    60    68  7.0  3.3       0.89
3   58    Male   1.0  0.4      182    14    20  6.8  3.4       1.00
4   72    Male   3.9  2.0      195    27    59  7.3  2.4       0.40

In [ ]:
x.isnull().sum()

Age          0
Gender       0
TB           0
DB           0
Alkphos      0
Sgpt         0
Sgot         0
TP           0
ALB          0
A/G Ratio    4
dtype: int64

In [ ]:
x.replace('Male',1, inplace=True)
x.replace('Female',0, inplace=True)
x.isnull().sum()

<ipython-input-37-1fe352816426>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x.replace('Female',0, inplace=True)

Age          0
Gender       0
TB           0
DB           0
Alkphos      0
Sgpt         0
Sgot         0
TP           0
ALB          0
A/G Ratio    4
dtype: int64

In [ ]:
x.head()

   Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB  A/G Ratio
0   65       0   0.7  0.1      187    16    18  6.8  3.3       0.90
1   62       1  10.9  5.5      699    64   100  7.5  3.2       0.74
2   62       1   7.3  4.1      490    60    68  7.0  3.3       0.89
3   58       1   1.0  0.4      182    14    20  6.8  3.4       1.00
4   72       1   3.9  2.0      195    27    59  7.3  2.4       0.40

In [ ]:
x['A/G Ratio'].fillna(x['A/G Ratio'].mean(), inplace=True)

<ipython-input-39-4aec544999fd>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x['A/G Ratio'].fillna(x['A/G Ratio'].mean(), inplace=True)

In [ ]:
x.isnull().sum()

Age          0
Gender       0
TB           0
DB           0
Alkphos      0
Sgpt         0
Sgot         0
TP           0
ALB          0
A/G Ratio    0
dtype: int64

In [ ]:
print(x)

     Age  Gender    TB   DB  Alkphos  Sgpt  Sgot   TP  ALB  A/G Ratio
0     65       0   0.7  0.1      187    16    18  6.8  3.3       0.90
1     62       1  10.9  5.5      699    64   100  7.5  3.2       0.74
2     62       1   7.3  4.1      490    60    68  7.0  3.3       0.89
3     58       1   1.0  0.4      182    14    20  6.8  3.4       1.00
4     72       1   3.9  2.0      195    27    59  7.3  2.4       0.40
..   ...     ...   ...  ...      ...   ...   ...  ...  ...        ...
578   60       1   0.5  0.1      500    20    34  5.9  1.6       0.37
579   40       1   0.6  0.1       98    35    31  6.0  3.2       1.10
580   52       1   0.8  0.2      245    48    49  6.4  3.2       1.00
581   31       1   1.3  0.5      184    29    32  6.8  3.4       1.00
582   38       1   1.0  0.3      216    21    24  7.3  4.4       1.50

[583 rows x 10 columns]

In [ ]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 583 entries, 0 to 582
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        583 non-null    int64
 1   Gender     583 non-null    int64
 2   TB         583 non-null    float64
 3   DB         583 non-null    float64
 4   Alkphos    583 non-null    int64
 5   Sgpt       583 non-null    int64
 6   Sgot       583 non-null    int64
 7   TP         583 non-null    float64
 8   ALB        583 non-null    float64
 9   A/G Ratio  583 non-null    float64
dtypes: float64(5), int64(5)
memory usage: 45.7 KB

In [ ]:
x.describe()

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,A/G Ratio
count,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000,583.000000
mean,44.746141,0.756432,3.298799,1.486106,290.576329,80.713551,109.910806,6.483190,3.141852,0.947064
std,16.189833,0.429603,6.209522,2.808498,242.937989,182.620356,288.918529,1.085451,0.795519,0.318492
min,4.000000,0.000000,0.400000,0.100000,63.000000,10.000000,10.000000,2.700000,0.900000,0.300000
25%,33.000000,1.000000,0.800000,0.200000,175.500000,23.000000,25.000000,5.800000,2.600000,0.700000
50%,45.000000,1.000000,1.000000,0.300000,208.000000,35.000000,42.000000,6.600000,3.100000,0.947064
75%,58.000000,1.000000,2.600000,1.300000,298.000000,60.500000,87.000000,7.200000,3.800000,1.100000
max,90.000000,1.000000,75.000000,19.700000,2110.000000,2000.000000,4929.000000,9.600000,5.500000,2.800000

In [ ]:
from imblearn.over_sampling import SMOTE
smote=SMOTE()
x,target=smote.fit_resample(x,target)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,target,test_size=0.2,random_state=42)

In [ ]:
x_train

,Age,Gender,TB,DB,Alkphos,Sgpt,Sgot,TP,ALB,A/G Ratio
477,55,1,0.600000,0.2,220,24,32,5.100000,2.400000,0.880000
346,46,1,0.600000,0.2,115,14,11,6.900000,3.400000,0.900000
462,38,1,0.700000,0.2,110,22,18,6.400000,2.500000,0.640000
671,17,1,0.825221,0.2,312,50,38,7.925221,3.850441,0.925221
302,50,0,1.700000,0.6,430,28,32,6.800000,3.500000,1.000000
...,...,...,...,...,...,...,...,...,...,...
71,75,0,0.800000,0.2,188,20,29,4.400000,1.800000,0.600000
106,36,1,5.300000,2.3,145,32,92,5.100000,2.600000,1.000000
270,37,1,0.700000,0.2,235,96,54,9.500000,4.900000,1.000000
435,17,0,0.500000,0.1,206,28,21,7.100000,4.500000,1.700000
102,17,1,0.900000,0.2,224,36,45,6.900000,4.200000,1.550000

#Perceptron

In [ ]:
from sklearn.linear_model import Perceptron
pm=Perceptron()
pm.fit(x_train,y_train)

Perceptron()

In [ ]:
yp=pm.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,yp))

[[57 18]
 [66 26]]

In [ ]:
print(classification_report(y_test,yp))

              precision    recall  f1-score   support

           1       0.46      0.76      0.58        75
           2       0.59      0.28      0.38        92

    accuracy                           0.50       167
   macro avg       0.53      0.52      0.48       167
weighted avg       0.53      0.50      0.47       167

In [ ]:
print(accuracy_score(y_test,yp))

0.49700598802395207


#LogisticRegression

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
yp = lr.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,yp))

[[49 26]
 [10 82]]

In [ ]:
print(classification_report(y_test,yp))

              precision    recall  f1-score   support

           1       0.83      0.65      0.73        75
           2       0.76      0.89      0.82        92

    accuracy                           0.78       167
   macro avg       0.79      0.77      0.78       167
weighted avg       0.79      0.78      0.78       167

In [ ]:
print(accuracy_score(y_test,yp))

0.7844311377245509

#Support Vector Mechine

In [ ]:
from sklearn.svm import SVC
sv=SVC()
sv.fit(x_train,y_train)

SVC()

In [ ]:
yp=sv.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,yp))

[[38 37]
 [13 79]]

In [ ]:
print(classification_report(y_test,yp))

              precision    recall  f1-score   support

           1       0.75      0.51      0.60        75
           2       0.68      0.86      0.76        92

    accuracy                           0.70       167
   macro avg       0.71      0.68      0.68       167
weighted avg       0.71      0.70      0.69       167

In [ ]:
print(accuracy_score(y_test,yp))

0.7005988023952096